name: fairtool install test

on:
  schedule:
    - cron: '0 3,15 * * *'
  workflow_dispatch:

jobs:
  install-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-24.04'
          - 'macos-14'
          - 'macos-15'
          - 'macos-15-intel'
          - 'macos-26'
    runs-on: ${{ matrix.os }}
    steps:
      - run: curl -fsSL https://appfair.net/install-fairtool.sh | sh
      - run: fairtool --version

